export const HEAD_TITLE =
  "CaDance | A fine tuned running and listening experience";
export const APP_TITLE = "CaDance";
export const APP_DESCRIPTION = "A fine tuned running and listening experience";
export const ACCESS_TOKEN_NAME = "access_token";
export const REFRESH_TOKEN_NAME = "refresh_token";
export const EXPIRATION_STRING = "expires_at";
export const LOGGED_IN_NO_USERNAME = "Logged in";
export const LOGGED_IN_USERNAME = "Logged in as ";
export const FIND_SONGS_TEXT = "FIND SONGS";
export const SAVE_AS_PLAYLIST_TEXT = "SAVE AS PLAYLIST";
export const OPEN_IN_SPOTIFY_TEXT = "OPEN PLAYLIST IN SPOTIFY";
export const SESSION_EXPIRED_TEXT = "Session expired. Please refresh page";
export const RATE_LIMIT_TEXT =
  "App has exceeded rate limit. Please contact the developer.";
export const PLAYLIST_NAME_BASE = "CaDance Running Playlist: ";
export const PLAYLIST_DESCRIPTION_BASE = "Playlist generated by CaDance";

export const SEX_SELECT_PLACEHOLDER = "Select your assigned sex...";

export const NUM_SONGS_SELECT_PLACEHOLDER = "Select number of songs...";

export const HEART_RATE_SELECT_PLACEHOLDER =
  "(Optional) Select your heart rate zone...";

export const GENRE_SELECT_PLACEHOLDER = "Select genres...";

export const MODE_TEXT_STANDARD = "Standard mode";
export const MODE_TEXT_WATCH = "Watch mode";

export const HEIGHT_TITLE = "Please enter your height";
export const HEIGHT_LABEL_FEET = "ft";
export const HEIGHT_LABEL_INCHES = "in";

export const ENERGY_LABEL_TEXT = "Energy:";
export const CADENCE_LABEL_TEXT = "Cadence:";

export const WEBPLAYER_LOADING_TEXT = "Loading...";
export const WEBPLAYER_PLAY = "PLAY";
export const WEBPLAYER_PAUSE = "PAUSE";
