import Head from "next/head";
import { ChangeEvent, ChangeEventHandler, useEffect, useState } from "react";
import { Metronome } from "../scripts/metronome";
import localFont from "next/font/local";
import { redirectToVerification } from "../api/spotify/testVerifier";
const variableFont = localFont({ src: "../../public/fonts/DS-Digital.woff2" });

//POTENTIAL TODO: check if the user is already logged in and redirect them to the logged in page if they are

export default function Home() {
  const [tempo, setTempo] = useState(100);
  const [metronome, setMetronome] = useState(new Metronome(tempo));
  const [metronomePlaying, setMetronomePlaying] = useState(false);
  const [selectedGenres, setSelectedGenres] = useState<string[]>([]);

  const handleChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    if (event.target) {
      console.log(event.target.value);
      if (!selectedGenres.includes(event.target.value)) {
        const copy = selectedGenres.slice();
        copy.push(event.target.value);
        setSelectedGenres(copy);
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="outer">
        <div className="inner">
          <h1 className="header">CADANCE</h1>
          <div className="log-in-buttons">
            <button onClick={redirectToVerification}>Login to Spotify</button>
          </div>
        </div>
      </div>
    </>
  );
}
