import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { ChangeEvent, ChangeEventHandler, useEffect, useState } from "react";
import { Metronome } from "../scripts/metronome";
import localFont from "next/font/local";
import Genre from "../components/Genre";
import { logout, exchangeToken } from "../api/spotify/PKCEVerifier";
const variableFont = localFont({ src: "../../public/fonts/DS-Digital.woff2" });
import { useRouter } from "next/router";
import { testButton } from "@/api/spotify/playlistBuilder";
import { MetronomeComponent } from "@/components/MetronomeComponent";

export default function LoggedIn() {
  const [tempo, setTempo] = useState(100);
  const [metronome, setMetronome] = useState(new Metronome(tempo));
  const [metronomePlaying, setMetronomePlaying] = useState(false);
  const [selectedGenres, setSelectedGenres] = useState<string[]>([]);
  const [numSongs, setNumSongs] = useState<number>();

  const router = useRouter();
  const { code } = router.query;

  //TODO: make code part of the state

  useEffect(() => {
    if (router.isReady) {
      if (code !== undefined) {
        exchangeToken(code);
      } else if (
        localStorage.getItem("access_token") &&
        localStorage.getItem("refresh_token") &&
        localStorage.getItem("expires_at")
      ) {
        //TODO: this is where we check if the user is already logged in, might need to put in a diff. file
      } else {
        router.push("/");
      }
    }
  }, [code]);

  const handleGenreChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    if (!selectedGenres.includes(event.target.value)) {
      const copy = selectedGenres.slice();
      copy.push(event.target.value);
      setSelectedGenres(copy);
    }
  };
  const handleNumChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const num = parseInt(event.target.value);
    setNumSongs(num);
  };

  //TODO: get the user's name from the spotify api and display it here
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="outer">
        <div className="inner">
          <h1 className="header">CADANCE</h1>
          <div className="log-in-buttons">
            <button className="spotify-button" onClick={logout}>
              Log Out
            </button>
            <button className="" onClick={testButton}>
              TEST
            </button>
          </div>

          <h3 className="switch-title">Metronome ON/OFF</h3>
          <div className="metronome-switch-div">
            <label className="switch">
              <input
                onChange={() => {
                  metronome.startStop();
                  setMetronomePlaying(!metronomePlaying);
                }}
                aria-label="metronome switch"
                type="checkbox"
              />
              <span className="slider round"></span>
            </label>
          </div>
          <MetronomeComponent
            tempo={tempo}
            setTempo={setTempo}
            metronome={metronome}
            max={300}
            min={50}
          ></MetronomeComponent>

          <div className="selectedOptions">
            {selectedGenres.length === 0 ? (
              <>
                <br></br>
                <br></br>
                <br></br>
              </>
            ) : (
              selectedGenres.map((val, i) => {
                return (
                  <Genre
                    key={i}
                    genre={val}
                    genres={selectedGenres}
                    setGenre={setSelectedGenres}
                  ></Genre>
                );
              })
            )}
          </div>

          <div className="dropdown-div">
            <select
              name="genre"
              value={
                selectedGenres.length === 0
                  ? "disabled"
                  : selectedGenres[selectedGenres.length - 1]
              }
              onChange={handleGenreChange}
              className="dropdown hvr-grow"
            >
              <option disabled value={"disabled"}>
                Select desired genres
              </option>
              <option value="test1">test1</option>
              <option value="test2">test2</option>
              <option value="test3">test3</option>
              <option value="test4">test4</option>
            </select>

            <select
              name="num-songs"
              onChange={handleNumChange}
              defaultValue={"disabled"}
              className="dropdown hvr-grow"
            >
              <option disabled value={"disabled"}>
                Select desired number of songs
              </option>
              {[...Array(10)].map((x, i) => {
                return (
                  <option key={i + 1} value={i + 1}>
                    {i + 1}
                  </option>
                );
              })}
            </select>
          </div>
          <div className="search-button-div">
            <button className="search-button hvr-grow">FIND SONGS</button>
          </div>
        </div>
      </div>
    </>
  );
}
